services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=development_database
      - MYSQL_ROOT_PASSWORD=development_root_password
      - MYSQL_USER=development_user
      - MYSQL_PASSWORD=development_password
    ports:
      - 3306:3306 # ホストのポート3306とMySQLコンテナのポート3306をつなぐ
    volumes:
      - db_data:/var/lib/mysql # /var/lib/mysqlに保存されるMySQLのデータをコンテナの外のDocker Volumeにマウントする

volumes:
  db_data:

