openapi: 3.0.4
info:
  title: 内部API
  description: オンラインカートシステムが利用する内部API
  version: 1.0.0

# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

paths:
  /v1/users:
    summary: 会員登録API（ユーザー作成）
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usercode:
                  $ref: "#/components/schemas/usercode"
                password:
                  $ref: "#/components/schemas/password"
              required:
                - usercode
                - password
      responses:
        "201":
          description: ユーザーの登録成功
        "400":
          description: バリデーションエラー

components:
  schemas:
    usercode:
      type: string
      description: 任意のユーザーコード
      example: user_code_1
      minLength: 8
      maxLength: 30
      pattern: "^[a-za-z0-9_]+$"
      x-oapi-codegen-extra-tags:
        validate: "required,min=8,max=30"
    password:
      type: string
      description: 任意のパスワード（8〜64文字、英数記号）
      example: dhfh34ufds
      minLength: 8
      maxLength: 64
      pattern: ^[\x21-\x7e]{8,64}$
      x-oapi-codegen-extra-tags:
        validate: "required,min=8,max=64"

