openapi: 3.0.4
info:
  title: 内部API
  description: オンラインカートシステムが利用する内部API
  version: 1.0.0

# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

paths:
  /v1/users:
    summary: 会員登録API（ユーザー作成）
    $ref: "./paths/v1/users/post.yml"

components:
  schemas:
    usercode:
      type: string
      description: 任意のユーザーコード
      example: user_code_1
      minlength: 8
      maxlength: 30
      pattern: "^[a-za-z0-9_]+$"
    password:
      type: string
      description: 任意のパスワード（8〜64文字、英数記号）
      example: dhfh34ufds
      minlength: 8
      maxlength: 64
      pattern: ^[\x21-\x7e]{8,64}$

